apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespaceName }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | .Values.service.port }}
  type: {{ .Values.service.type }}
